#!/bin/bash

set -ex

# Don't push images if branch is not main
echo "Current Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "main" ]; then
    exit 0
fi

for tag in $(docker images norby/node-alpine --format "{{.Tag}}");
do
    docker push "norby/node-alpine:${tag}"
done